name: AAOS CI

on:
  push:
    branches:
      - 'staging/**'
      - 'epic/**'
      - 'task/**'
      - 'bug/**'

jobs:
  build-and-test:
    runs-on: gha-internal-hc-amd64
    if: startsWith(github.ref, 'refs/heads/task/') || startsWith(github.ref, 'refs/heads/bug/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Chmod permissions
        run: sudo chmod +x ./gradlew

      - name: Enable KVM
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm
          
      - name: Run Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 34
          script: ./gradlew lib:connectedDebugAndroidTest

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            lib/build/outputs/androidTest-results/**/*.xml